FROM centos:latest
ENV container docker
MAINTAINER "Jordan Wamser" <jwamser@vortexglobal.com>

RUN yum -y update
RUN yum -y install epel-release \
                   wget \
                   yum-utils
RUN wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN rpm -Uvh remi-release-7*.rpm
RUN yum-config-manager --enable remi-php71
RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN ACCEPT_EULA=Y yum install -y msodbcsql mssql-tools unixODBC-devel
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN source ~/.bashrc
RUN yum install -y gettext \ 
               php-fpm \ 
               php-cli \
               php-common \
               php-gd \
               php-intl \
               php-json \
               php-ldap \
               php-mbstring \
               php-mcrypt \
               php-opcache \
               php-pdo \
               php-pecl-zip \
               php-soap \
               php-sqlsrv \
               php-xml \
               php-mysqlnd \
               php-pecl-uuid \
               php-bcmath \
               mediainfo \
               openldap-clients \
               php-mhash \
               php-xsl \
               php-pear \
               php-soap
RUN yum clean all 
 
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 9000

ADD container-files/script/* /tmp/script/
#COPY container-files/nginx.conf /etc/nginx/nginx.conf
#COPY container-files/vhost.conf /etc/nginx/conf.d/vhost.conf
COPY container-files/php.ini /etc/php.ini
COPY container-files/php-fpm.conf /etc/php-fpm.conf
COPY container-files/www.conf /etc/php-fpm.d/www.conf

#ADD container-files/script/* /tmp/script/
#RUN chmod +x /tmp/script/bootstrap.sh

# put customized config and code files to /data

ENTRYPOINT ["/tmp/script/bootstrap.sh"]
#CMD ["php-fpm","--allow-to-run-as-root","--nodaemonize"]
