version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx
        networks:
            - code-network
    php:
        # image: php:fpm
        build: ./phpfpm/
        environment:
            ENABLE_XDEBUG: 1
        volumes:
            - ./code:/code
        networks:
            - code-network
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - web

networks:
    code-network:
        driver: bridge
