version: '2.1'

services:
#jw-todo: add depends_on options to services.
    web:
            image: nginx:latest
            ports:
                - "8080:80"
            volumes:
                - ./code:/code
                - ./old/site.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./php
        image: rpc_php:latest
        environment:
            ENABLE_XDEBUG: "1"
        volumes:
            - ./code:/code
#            - ./logs/php:/var/log/php-fpm
