version: '2.1'

services:
#jw-todo: add depends_on options to services.
    web:
        build: ./NginX/
        depends_on:
          - php
        image: rpc_nginx:latest
        ports:
            - "8080:9050"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
#        networks:
#            code_network:

    php:
        build: phpfpm
        image: rpc_php:latest
#        environment:
#            ENABLE_XDEBUG: "1"
        volumes:
            - ./code:/code
            - ./logs/php:/var/log/php-fpm
#        networks:
#            code_network:
#                link_local_ips:
#                  - 10.10.13.135

    # elk:
    #     image: willdurand/elk
    #     ports:
    #         - 81:80
    #     volumes:
    #         - ./elk/logstash:/etc/logstash
    #         - ./elk/logstash/patterns:/opt/logstash/patterns
    #     volumes_from:
    #         - php
    #         - web

#networks:
#    code_network:
#        driver: bridge
